JWT expiration check
pysnippet/fastapi-oauth2 pull request #43
Opened 2024-07-20 18:27 UTC by Scurrra

### Motivation:

Doing a project I found this library for easy oauth. Because of lack of experience in the field I decided to learn how the library works. I had a big question on how jwts work, especially in this library. While doing this I found out that there is no check if the token is expired. I added this check to OAuth2Backend.authenticate. I also fixed deprecated datetime.utcnow() function.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing](./CONTRIBUTING.md) document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you updated the documentation related to the changes you have made?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

2024-07-21 09:44 UTC, ArtyomVancyan requested changes
Hi @Scurrra, thanks for pointing it out. I suggest changing the `UTC` alias with `timezone.utc` as it is not available in all versions of the `datetime` package.

2024-07-21 09:44 UTC, ArtyomVancyan commented on src/fastapi_oauth2/middleware.py
> +from datetime import UTC
```suggestion
from datetime import timezone
```

2024-07-21 09:44 UTC, ArtyomVancyan commented on src/fastapi_oauth2/middleware.py
> +        expire = datetime.now(UTC) + timedelta(seconds=cls.expires)
```suggestion
        expire = datetime.now(timezone.utc) + timedelta(seconds=cls.expires)
```

2024-07-21 09:44 UTC, ArtyomVancyan commented on src/fastapi_oauth2/middleware.py
> +        if token_data["exp"] and token_data["exp"] < int(datetime.now(UTC).timestamp()):
```suggestion
        if token_data["exp"] and token_data["exp"] < int(datetime.now(timezone.utc).timestamp()):
```

2024-07-21 13:32 UTC, ArtyomVancyan commented
@Scurrra, you requested me a review, but I requested a few changes before merging (you shouldn't click "Resolve", you should do "Commit suggestion"). I will wait for your update. Also, I didn't get what was wrong with the old `datetime.utcnow()`. Isn't that the same as what you suggested (`datetime.now(UTC)`)?

2024-07-21 13:38 UTC, Scurrra commented
> you should do "Commit suggestion"
My bad, sorry.

datetime.utcnow() will be deprecated.

2024-07-21 14:06 UTC, merged

2024-07-23 17:28 UTC, Scurrra commented
I don't know is it my fault or not, but playground is broken.

![image](https://github.com/user-attachments/assets/ecae4d3d-026c-477c-bda3-980b8dcad2fc)

Probably this is because of troubles with OAUTH2_GITHUB_CLIENT_ID in playground, which wasn't affected by me.

2024-07-23 17:54 UTC, ArtyomVancyan commented
It was a missdeployment issue, I have fixed it. Thanks for letting me know. Also, it could not be your fault, as these changes haven't been released yet :)